void-linux/void-runit

3, core-services/05-misc.sh, core-services/99-cleanup.sh, halt.8, halt.c
This implements -w and -d.
Also add -B to create boot-time wtmp entries.
Closes #27.
=> halt: add support for wtmp

core-services/08-sysctl.sh
Loading of sysctl.d directories should follow the same ordering and
overriding rules as xbps, modules-load, and most importantly,
`sysctl --system`.
This change ensures proper ordering of files loaded by building the
selected files then operating on them, and it allows for masking system
level configuration from /etc and even /run.
=> fix(sysctl): behave more like sysctl --system

core-services/05-misc.sh
Regenerating the stored seed was an attempt to prevent hard shutdowns
from leading to seed reuse.
Unfortunately, this practice depletes any entropy that was added by
the seed.
Furthermore on newer kernels which do not credit entropy added from
userspace, the operation is often an uninitialized read of urandom.
=> fix(urandom): avoid uninitialized read during boot

core-services/00-pseudofs.sh
The pseudofs script currently mounts cgroup v1 file systems in the /sys/fs/cgroup hierarchy, but does not mount the cgroup v2 file system at /sys/fs/cgroup/unified. This PR will mount the cgroup v2 file system provided it is not already mounted and "cgroup2" is listed in /proc/filesystems.
=> core-services/00-pseudofs.sh: mount cgroup v2 unified file system

crypt.awk
With encrypted swap using disposable keys (`/dev/urandom`), one cannot use a `UUID` because there is no consistent UUID associated with the swap device. A better specifier is PARTUUID, which is a property of the partition table that will not change with each invocation of `mkswap`. This alters the `crypt.awk` script to recognize device specifiers of the form `PARTUUID=<partition-uuid>` as it does `UUID` to properly detect swap devices.
=> crypt.awk: support PARTUUID in /etc/crypttab

1, 3, ctrlaltdel
Fixes #47 
Since the `halt` program seems to use `init` directly, I don't think anything else needs to be changed.
Needs proper testing as well.
Ping @Duncaen and @leahneukirchen
=> Fix `ctrlaltdel` and `1` for stopit and reboot files

rc.conf
Recommend users to symlink their timezone to /etc/localtime instead of
setting TZ in /etc/rc.conf.
Following @Duncaen 's recommendation.
=> rc.conf: add note recommending /etc/localtime

core-services/03-filesystems.sh
This fixes early-boot automounting for users of native encryption in ZFS.
`zfs mount -a` will mount every ZFS filesystem with a valid `mountpoint` property and not explicitly prevented from mounting or automounting---except for any encrypted filesystem protected with a key that has not previously been loaded. At early boot, the only key that has been loaded is the one needed for the root mount, so any other encrypted filesystem with a different `encryptionroot` will not be automounted.
Using `zfs mount -a -l` will cause ZFS to attempt to load any key it needs to auto-mount an encrypted filesystem. For filesystems whose `keylocation` properties are a `file:///` URL, this will happen silently. For filesystems with a `prompt` keylocation, this will block the terminal awaiting user entry for …
=> core-services/03-filesystems.sh: load keys as necessary when mounting

modules-load
Without this only the first occurrence of "," is replaced, causing
`modules-load=ab,cd,ef,gh`
to be parsed as
```
ab
cd,ef,gh
```
=> Use global substitution on commas in modules-load

services/agetty-generic/run
The setsid program has a surprise gotcha of backgrounding a process if
it already happens to be the session leader. This is ok for runit which
never sets the service as a session leader but does not work with other
supervisors which might. chpst provides the same setsid(2) functionality
without also having the gotcha.
=> services/agetty-generic: use chpst -P instead of setsid

core-services/03-filesystems.sh
If `auto_activation_volume_list` is set in `lvm.conf`, this action will ensure that its respected when activating.  If its unset, there should be no behavior change.
Closes #64.
=> core-services/03-filesystems.sh: respect auto_activation_volume_list

halt.c
The pending change to allow for alternate init power controls requires
that the halt binary provided here be somewhat less strict in its
argv[0] matching in order to allow for halt, reboot, and poweroff to
still function in situations where the binary has been renamed.
This switches from strcmp(__progname, "string") to strncmp(__progname,
"string", len), where len is the name of the power command sans any
suffix.
Signed-off-by: Colin Booth <colin@heliocat.net>
=> halt: switch __progname tests to use strncmp

core-services/00-pseudofs.sh, rc.conf
Some of the tooling with the support for cgroups v2 (notably container tools like podman, crun and runc) [check](https://github.com/containers/podman/blob/8b377a79c240e4480339358db3b87263ec6cfef3/pkg/cgroups/cgroups_supported.go#L25-L35) `cgroup v2` availability via the fs magic number on  the `/sys/fs/cgroup`. Hybrid mode (used by void) is not as useful afaik due to inability to map v1 and v2 controllers at the same time. This patch introduces support for pure v1 (legacy) and v2 (unified) cgroups mounts while preserving the current v2 under v1 (hybrid) mode as a default. These modes are modeled after [OpenRC](https://github.com/OpenRC/openrc/blob/72df51e17ba0e1a0f94451b4bbfb338288c4625c/init.d/cgroups.in#L121-L129).
=> Support pure v2 cgroup mounts

.gitignore, 3, Makefile, core-services/05-misc.sh, rc.conf, seedrng.c
The RNG can't actually be seeded from a shell script, due to the reliance on ioctls. For this reason, the seedrng project provides a basic script meant to be copy and pasted into projects like void-runit and tweaked as needed: <https://git.zx2c4.com/seedrng/about/>.
This commit imports it into void-runit and wires up the init scripts to call it. This also is a significant improvement over the current init script, which fails to remove seed files that have already been used, or to ratchet them forward.
=> Use seedrng for seeding the random number generator

core-services/00-pseudofs.sh
Since we switched to CONFIG_EFIVAR_FS, this needs to be mounted explicitly for things like efibootmgr to work.
Systemd also mounts it on boot, so in core-services should be fine.
The `[ -d ]` should gate EFI boots only.
=> core-services/00-pseudofs: mount /sys/firmware/efi/efivars when appropriate

core-services/03-filesystems.sh
My Void server reboots to the emergency shell every time, because I have a software RAID 5 array in `/etc/fstab` that's never started.
I suspect that other people are using mdadm arrays without issue and I could be missing something elsewhere, perhaps in dracut, but a PR is as fine a place as any to hash that out.
=> Activate mdadm arrays on boot

crypt.awk
Reference: https://wiki.archlinux.org/title/Dm-crypt/Specialties#Disable_workqueue_for_increased_solid_state_drive_(SSD)_performance
adds no-read-workqueue,no-write-workqueue options.
=> cryptsetup,crypttab - Optional performance enhacement for fast ssds

functions
Some of the functions had 3 leading spaces instead of 4.
=> functions: fix indentation

shutdown.d/90-kexec.sh
I have recently fooled around with kexec and found a small issue. Commits 05c6e86e085e0c0fdfc84a013477efd51e700845 and df580011835bff76fc0d4473f52344898abd9ef5 changed how `/run/runit/reboot` works, which results in `if [ -e /run/runit/reboot ]` always evaluating to true. This means that when the system is trying to shut down, not reboot, and kexec-tools is installed, it will try to kexec into a new kernel. Of course, this fails when there is no kernel loaded for kexec, but if there is one the system will reboot instead of shutting it down.
Changing the line to an executable check on `/run/runit/reboot` makes it work as expected on my end, trying to kexec on reboot but not on shutdown.
=> Only try to run kexec on reboot

crypt.awk
This enables handling of the following options:
* perf-same_cpu_crypt
* perf-submit_from_crypt_cpus
* perf-no_read_workqueue
* perf-no_write_workqueue
=> crypt.awk: enable dm-crypt perf-* options

functions
effectively informs user that encryption key(s) have been securely erased prior to potentially rebooting which would leave memory energized
=> inform user that encrypted volume was successfully closed

core-services/03-filesystems.sh, shutdown.d/80-filesystems.sh
With util-linux>=2.40, filesystems that do not support remounting with different options fail because the new kernel mount interface is used. This breaks booting an overlayfs (like live ISOs).
By setting `LIBMOUNT_FORCE_MOUNT2=always`, we force `mount(8)` to use the old kernel mount interface, which ignores changed options.
Tested in mklive to ensure overlayfs root works.
see also:
* https://github.com/util-linux/util-linux/issues/2576
* https://github.com/void-linux/void-mklive/issues/369
=> core-services/03-filesystems.sh: force legacy mount iface for remount

1, core-services/10-runit-control.sh, core-services/97-dmesg.sh
Based 100% on the work by @sbromberger
#113
I didn't want the work to die.
After this change, folks using lxd or incus containers will be able to create their own lower-priority core service to modify the permissions on the files to enable proper shutdown/reboot of the containers. These core services will survive upgrades to void-runit, unlike the current approach in the container script.
=> 1, core-services: migrate towards core-services

core-services/00-pseudofs.sh, rc.conf
Default to cgroup2
Attempt to mount cgroup2 in containers to support nesting
Mount the systemd tracking cgroup when using cgroup1
Closes https://github.com/void-linux/void-runit/issues/74
---
Former title: rough thoughts on cgroup1 and cgroup2  
Former description:
cgroup1
the various container tool run scripts variably handle certain cases,
namely that of the systemd tracking cgroup.
i am actually not 100% confident on why that cgroup needs to be mounted,
but i imagine it has to do with the needs of systemd instances that may
be running in containers.
anyway supposedly it needed to be mounted at one point so the run
scripts would do it. but if the run scripts did it, it could not have
been that harmful. so just do it always. (in legacy/hybrid mode, which I
have not been using for some …
=> pseudofs: cgroup: various improvements
